# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('thesisinternetrouting', ['core','mcast','internet', 'wifi','mobility','csma','point-to-point','applications'])
    module.source = [
        'model/thesisinternetrouting.cc',
        'helper/thesisinternetrouting-helper.cc',
        'model/Thesis-Internet-Routing-Queue.cc',
        'model/InternetHeader.cc',
        'Application/ThesisPing6.cc',
        'helper/ThesisPing6Helper.cc',
        'model/thesisinternetrouting2.cc',
        'helper/thesisinternetrouting-helper2.cc',
        'model/RsuCache.cc',
        'Application/ThesisUdpEchoServer.cc',
        'Application/ThesisUdpEchoClient.cc',
        'helper/ThesisUdpEchoHelper.cc',
        'model/ITVHeader.cc',
        'model/GeoRequestHeader.cc',
        'Application/GeoQueryClient.cc',
        'helper/GeoClientHelper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('thesisinternetrouting')
    module_test.source = [
        'test/thesisinternetrouting-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'thesisinternetrouting'
    headers.source = [
        'model/thesisinternetrouting.h',
        'helper/thesisinternetrouting-helper.h',
        'model/Thesis-Internet-Routing-Queue.h',
        'model/InternetHeader.h',
        'Application/ThesisPing6.h',
        'helper/ThesisPing6Helper.h',
        'model/thesisinternetrouting2.h',
        'helper/thesisinternetrouting-helper2.h',
        'model/RsuCache.h',
        'Application/ThesisUdpEchoServer.h',
        'Application/ThesisUdpEchoClient.h',
        'helper/ThesisUdpEchoHelper.h',
        'model/ITVHeader.h',
        'model/GeoRequestHeader.h',
        'Application/GeoQueryClient.h',
        'helper/GeoClientHelper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

