# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
 #   obj = bld.create_ns3_program('mcast-example', ['mcast'])
 #   obj.source = 'mcast-example.cc'
    
    obj = bld.create_ns3_program('mcast-example2', ['mcast'])
    obj.source = 'mcast-example2.cc'
    
    obj = bld.create_ns3_program('dbtest', ['mcast'])
    obj.source = 'DbTest.cc'

